# Generated by Django 2.0.6 on 2019-07-18 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='user_profilepics')),
                ('phone_number', models.CharField(default=None, max_length=10)),
                ('gender', models.IntegerField(default=0)),
                ('address', models.CharField(default=None, max_length=50)),
                ('auth_level', models.IntegerField(default=1)),
                ('device_type', models.CharField(default='website', max_length=20)),
                ('device_token', models.CharField(default='0', max_length=150)),
                ('role', models.CharField(default='customer', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
