# Generated by Django 2.0.6 on 2019-07-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='auth_level',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
